title:              NCBO
email:              your-email@example.com
description:        Official website of the North Carolina Baroque Orchestra
author:             North Carolina Baroque Orchestra. A 501(c)(3) organization.
baseurl:            "/ncboweb/"
url:                ""

# Social Profiles
twitter_username:  
github_username:    
facebook_username:  ncbaroqueorchestra
instagram_username:  ncbaroqueorchestra
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

